name: mygamelist
description: A game tracking and discovery app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  intl: ^0.20.1
  xml: ^6.5.0
  flutter_widget_from_html: ^0.15.2
  wakelock_plus: ^1.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
